name: nyxx_extensions
version: 1.0.0
description: Extensions for Nyxx library
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issue

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  nyxx: "^1.0.0"
  http: "^0.12.2"

dev_dependencies:
  dart_style:
  analyzer:
