name: Deploy to pub
on:
  workflow_dispatch:
    inputs:
        package-name:
          description: 'Package name'
          default: 'nyxx'
          required: true
        dry:
          description: 'True if dry run, or false to publish'
          default: 'true'
          required: true

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4 
      
      - name: Setup Dart Action
        uses: cedx/setup-dart@v2.3.0
        with:
         release-channel: dev
         
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          package_directory: ${{ github.event.inputs.package-name }}
          flutter_package: false
          skip_test: true
          dry_run: true
